export const initialTasks = {
  section1: [
    {
      id: 'task-1',
      title: '할 일 초안 정리',
      memo: '종이 메모에서 디지털로 정리',
      date: '2025-03-01',
      tags: { type: 'Thinking' as const, category: 'personal' },
    },
    {
      id: 'task-2',
      title: 'UI 피드백 반영',
      memo: '디자이너 의견 반영하여 수정',
      date: '2025-03-02',
      tags: { type: 'Todo' as const, category: 'work' },
    },
    {
      id: 'task-1-1',
      title: '스크롤 테스트 1',
      memo: '스크롤 테스트를 위한 메모입니다.',
      date: '2025-03-03',
      tags: { type: 'Thinking' as const, category: 'dev' },
    },
    {
      id: 'task-1-2',
      title: '스크롤 테스트 2',
      memo: '스크롤 테스트를 위한 메모입니다.',
      date: '2025-03-04',
      tags: { type: 'Todo' as const, category: 'work' },
    },
    {
      id: 'task-1-3',
      title: '스크롤 테스트 3',
      memo: '스크롤 테스트를 위한 메모입니다.',
      date: '2025-03-05',
      tags: { type: 'Thinking' as const, category: 'personal' },
    },
    {
      id: 'task-1-4',
      title: '스크롤 테스트 4',
      memo: '스크롤 테스트를 위한 메모입니다.',
      date: '2025-03-06',
      tags: { type: 'Todo' as const, category: 'study' },
    },
    {
      id: 'task-1-5',
      title: '스크롤 테스트 5',
      memo: '스크롤 테스트를 위한 메모입니다.',
      date: '2025-03-07',
      tags: { type: 'Thinking' as const, category: 'health' },
    },
  ],
  section2: [
    {
      id: 'task-4',
      title: '마케팅 보고서 정리',
      memo: '카페24 자료 기반 요약',
      date: '2025-03-08',
      tags: { type: 'Todo' as const, category: 'marketing' },
    },
    {
      id: 'task-3',
      title: '캘린더 컴포넌트 정리',
      memo: 'FloatingCalendar 개선 필요',
      date: '2025-03-09',
      tags: { type: 'Thinking' as const, category: 'dev' },
    },
    {
      id: 'task-2-1',
      title: '스크롤 테스트 1',
      memo: '스크롤 테스트를 위한 메모입니다.',
      date: '2025-03-10',
      tags: { type: 'Thinking' as const, category: 'work' },
    },
    {
      id: 'task-2-2',
      title: '스크롤 테스트 2',
      memo: '스크롤 테스트를 위한 메모입니다.',
      date: '2025-03-11',
      tags: { type: 'Todo' as const, category: 'personal' },
    },
    {
      id: 'task-2-3',
      title: '스크롤 테스트 3',
      memo: '스크롤 테스트를 위한 메모입니다.',
      date: '2025-03-12',
      tags: { type: 'Thinking' as const, category: 'study' },
    },
  ],
  section3: [
    {
      id: 'task-5',
      title: '캘린더 오늘 표시 개선',
      memo: 'isToday 함수로 강조 처리',
      date: '2025-03-13',
      tags: { type: 'Todo' as const, category: 'dev' },
    },
    {
      id: 'task-3-1',
      title: '스크롤 테스트 1',
      memo: '스크롤 테스트를 위한 메모입니다.',
      date: '2025-03-14',
      tags: { type: 'Thinking' as const, category: 'health' },
    },
    {
      id: 'task-3-2',
      title: '스크롤 테스트 2',
      memo: '스크롤 테스트를 위한 메모입니다.',
      date: '2025-03-15',
      tags: { type: 'Todo' as const, category: 'work' },
    },
    {
      id: 'task-3-3',
      title: '스크롤 테스트 3',
      memo: '스크롤 테스트를 위한 메모입니다.',
      date: '2025-03-16',
      tags: { type: 'Thinking' as const, category: 'personal' },
    },
  ],
  section4: [
    {
      id: 'task-6',
      title: '리팩토링 작업 목록 정리',
      memo: '중복 로직 정리 필요',
      date: '2025-03-17',
      tags: { type: 'Todo' as const, category: 'dev' },
    },
    {
      id: 'task-7',
      title: '타입 분리하기',
      memo: '타입 분리를 통한 컴포넌트 독립성 향상',
      tags: { type: 'Thinking' as const, category: 'category' },
    },
    {
      id: 'task-4-1',
      title: '스크롤 테스트 1',
      memo: '스크롤 테스트를 위한 메모입니다.',
      date: '2025-03-18',
      tags: { type: 'Thinking' as const, category: 'study' },
    },
    {
      id: 'task-4-2',
      title: '스크롤 테스트 2',
      memo: '스크롤 테스트를 위한 메모입니다.',
      date: '2025-03-19',
      tags: { type: 'Todo' as const, category: 'health' },
    },
    {
      id: 'task-4-3',
      title: '스크롤 테스트 3',
      memo: '스크롤 테스트를 위한 메모입니다.',
      date: '2025-03-20',
      tags: { type: 'Thinking' as const, category: 'work' },
    },
    {
      id: 'task-4-4',
      title: '스크롤 테스트 4',
      memo: '스크롤 테스트를 위한 메모입니다.',
      date: '2025-03-21',
      tags: { type: 'Todo' as const, category: 'personal' },
    },
  ],
};

export const completedTasks = [
  {
    id: 'task-c1',
    title: '피그마 정리',
    memo: '전체 UI 흐름 구조화 완료',
    date: '2025-03-01',
    tags: { type: 'Todo' as const, category: 'design' },
  },
  {
    id: 'task-c2',
    title: '마케팅 자료 공유',
    memo: '팀 노션에 업로드 완료',
    date: '2025-03-02',
    tags: { type: 'Todo' as const, category: 'marketing' },
  },
  {
    id: 'task-c3',
    title: '공통 UI 컴포넌트 설계',
    memo: 'DragOverlayCard 등 재사용 모듈 설계함',
    date: '2025-03-03',
    tags: { type: 'Thinking' as const, category: 'dev' },
  },
];
