version: "3.8"

services:
  app:
    container_name: spring-app
    image: "${DOCKER_USERNAME}/iambohyun:latest"
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - redis

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
